---
  - name: Demo Playbook
    hosts: localhost
    connection: local

    tasks:
      - name: Count Cloud modules
        ansible_modules_counter: 
          modules_type: cloud
        register: cloud_modules_counter
      
      - name: Print Out Cloud Module Count
        debug:
          msg: "{{cloud_modules_counter}}"

      - name: Count Windows modules
        ansible_modules_counter: 
          modules_type: windows
        register: windows_modules_counter
      
      - name: Print Out Windows Modules Count
        debug:
          msg: "{{windows_modules_counter}}"
        
        
  