---
  - name: Demo Playbook
    hosts: localhost
    connection: local

    tasks:
      - name: Count Cloud modules
        ansible_modules_counter: 
          modules_type: cloud
        register: cloud_modules_counter
      
      - name: Print Out Cloud Module Count
        debug:
          msg: "{{cloud_modules_counter}}"

      - name: Count Command modules
        ansible_modules_counter: 
          modules_type: commands
        register: command_modules_counter
      
      - name: Print Out Command Modules Count
        debug:
          msg: "{{command_modules_counter}}"
        
        
  