---
  - name: Demo Playbook
    hosts: localhost
    connection: local

    tasks:
      - name: Ansible All Modules Counter
        ansible_modules_counter: 
          modules_type: "all"
        register: monitoring_module_return
      
      - name: Print Out Module Return
        debug:
          msg: "{{monitoring_module_return}}"

      - name: Ansible Cloud Modules Counter
        ansible_modules_counter: 
          modules_type: "clouds"
        register: cloud_module_return
      
      - name: Print Out Module Return
        debug:
          msg: "{{cloud_module_return}}"
        
        
  